#!/usr/bin/env python3

import glob
import json
import os


errors = 0
index = {
    '_note': 'Automatically generated by tools/update-index.py',
}
rootdir = os.path.join(os.path.dirname(__file__), '..')
names_to_maps = {}
names_to_roms = {}

# make sure ROMs listed in maps appear in romnames.json
with open(os.path.join(rootdir, 'romnames.json')) as f:
    romnames = json.load(f)

maps = os.path.join(rootdir, 'maps', '**', '*.map.json')
for map_file in glob.glob(maps, recursive=True):
    with open(map_file, 'r') as f:
        map_json = json.load(f)
        metadata = map_json.get('_metadata', {})
        roms = metadata.get('roms')
        platform = metadata.get('platform')
        if not roms:
            errors += 1
            print("Error: %s is missing a _metadata.roms entry" % map_file)
        elif not platform:
            errors += 1
            print("Error: %s is missing a _metadata.platform entry" % map_file)
        elif not os.path.isfile(os.path.join(rootdir, 'platforms', platform + '.json')):
            errors += 1
            print("Error: %s is missing platform file %s" % (map_file, platform))
        else:
            for rom in roms:
                name = romnames.get(rom)
                if not name:
                    errors += 1
                    print("Error: %s (from %s) does not appear in romnames.json" % (rom, map_file))
                if index.get(rom):
                    errors += 1
                    print("Error: %s appears in %s and %s" % (rom, index[rom], map_file))
                path = os.path.relpath(map_file, rootdir)
                index[rom] = path
                if name in names_to_maps:
                    print("Warning: multiple ROMs named %s" % name)
                names_to_maps[name] = path
                names_to_roms[name] = rom

with open(os.path.join(rootdir, 'index.json'), 'w') as f:
    f.write(json.dumps(index, indent=2, sort_keys=True))
    f.write('\n')   # include trailing newline

with open(os.path.join(rootdir, 'maplist.md'), 'w') as f:
    map_paths = []
    for name, path in sorted(names_to_maps.items()):
        if path not in map_paths:
            map_paths.append(path)
        f.write('* [%s][%u] _%s_\n' % (name, map_paths.index(path) + 1, names_to_roms.get(name)))
    f.write('\n')
    for index, path in enumerate(map_paths):
        f.write('[%u]: %s\n' % (index + 1, path))

exit(errors)
